name: PR checks
on: pull_request

jobs:
  test-build:
    runs-on: ubuntu-latest
    container:
      image: jekyll/jekyll
    steps:
      - uses: actions/checkout@v2

      - name: Check the site builds
        run: |
          mkdir .jekyll-cache _site
          jekyll build

      - name: Install curl
        run: |
          apk add curl

      - name: Serve the site, check it's accessible
        run: |
          jekyll serve &
          sleep 1
          curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://127.0.0.1:4000/practices/

  check-prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install yarn dependencies
        run: yarn install

      - name: Run Prettier over all files
        run: yarn prettier-check
