name: PR checks
on: pull_request

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install --yes ruby-bundler
          bundle install

      - name: Build the site resources
        run: jekyll build

      - name: Run the site, check it's accessible
        run: |
          jekyll serve &
          sleep 1
          curl --head --fail --retry-delay 5 --retry 10  --retry-connrefused http://127.0.0.1:4000/practices/

  check-prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install yarn dependencies
        run: yarn install

      - name: Run Prettier over all files
        run: yarn prettier-check
